# Generated by Django 4.1.6 on 2023-02-07 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('code', models.CharField(max_length=64)),
                ('brand', models.IntegerField(choices=[(1, 'Citadel'), (2, 'Vallejo'), (3, 'Tamiya')])),
                ('type', models.IntegerField(choices=[(1, 'Regular'), (2, 'Wash'), (3, 'Ink'), (4, 'Contrast'), (5, 'Other')])),
            ],
        ),
    ]
