# Generated by Django 3.2.22 on 2023-12-08 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='New_Paint_Analogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('New_Citadel', models.CharField(max_length=64, null=True)),
                ('Old_Citadel', models.CharField(max_length=64, null=True)),
                ('Vallejo_Game_Color', models.CharField(max_length=64, null=True)),
                ('VGC_Code', models.FloatField(max_length=64, null=True)),
                ('Vallejo_Model_Color', models.CharField(max_length=64, null=True)),
                ('VMC_Code', models.FloatField()),
                ('Vallejo_Model_Air', models.CharField(max_length=64, null=True)),
                ('VMA_Code', models.FloatField(max_length=64, null=True)),
                ('Rackham', models.CharField(max_length=64, null=True)),
                ('Privateer_Press', models.CharField(max_length=64, null=True)),
                ('Hex_Code', models.CharField(max_length=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('code', models.CharField(max_length=64, null=True)),
                ('brand', models.IntegerField(choices=[(1, 'Citadel'), (2, 'Vallejo'), (3, 'Tamiya')])),
                ('type', models.IntegerField(choices=[(1, 'Regular'), (2, 'Wash'), (3, 'Ink'), (4, 'Contrast'), (5, 'Spray'), (6, 'Other')])),
                ('analog', models.ManyToManyField(related_name='_WykazFarb_paint_analog_+', to='WykazFarb.Paint')),
            ],
        ),
        migrations.CreateModel(
            name='Paint_Sets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('paints', models.ManyToManyField(to='WykazFarb.Paint')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('paint_sets', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WykazFarb.paint_sets')),
                ('paints', models.ManyToManyField(to='WykazFarb.Paint')),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contains', models.ManyToManyField(to='WykazFarb.Paint')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
