# Generated by Django 4.1.6 on 2023-02-08 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WykazFarb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paint',
            name='code',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('paints', models.ManyToManyField(to='WykazFarb.paint')),
            ],
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('paints', models.ManyToManyField(to='WykazFarb.paint')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WykazFarb.user')),
            ],
        ),
    ]
