# Generated by Django 3.2.22 on 2023-12-08 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WykazFarb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_paint_analogs',
            name='VMC_Code',
            field=models.FloatField(max_length=64, null=True),
        ),
    ]
