# Generated by Django 3.2.22 on 2023-10-09 07:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('WykazFarb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paint',
            name='analog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='WykazFarb.paint'),
        ),
        migrations.AlterField(
            model_name='paint',
            name='code',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='paint',
            name='type',
            field=models.IntegerField(choices=[(1, 'Regular'), (2, 'Wash'), (3, 'Ink'), (4, 'Contrast'), (5, 'Spray'), (6, 'Other')]),
        ),
        migrations.CreateModel(
            name='Paint_Sets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('paints', models.ManyToManyField(to='WykazFarb.Paint')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contains', models.ManyToManyField(to='WykazFarb.Paint')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
