# Generated by Django 3.2.22 on 2023-12-08 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WykazFarb', '0002_alter_new_paint_analogs_vmc_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new_paint_analogs',
            name='Hex_Code',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
