# Generated by Django 4.1.6 on 2023-02-09 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WykazFarb', '0002_alter_paint_code_user_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paint',
            name='type',
            field=models.IntegerField(choices=[(1, 'Regular'), (2, 'Wash'), (3, 'Ink'), (4, 'Contrast'), (5, 'Spray'), (6, 'Other')]),
        ),
        migrations.CreateModel(
            name='Analog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analog', models.ManyToManyField(to='WykazFarb.paint')),
            ],
        ),
    ]
