# Generated by Django 3.2.22 on 2023-11-27 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('WykazFarb', '0002_auto_20231127_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='element',
            name='paint_sets',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='WykazFarb.paint_sets'),
        ),
        migrations.AlterField(
            model_name='paint_sets',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
