# Generated by Django 4.1.6 on 2023-02-09 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WykazFarb', '0003_alter_paint_type_analog'),
    ]

    operations = [
        migrations.AddField(
            model_name='paint',
            name='analog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='WykazFarb.paint'),
        ),
        migrations.DeleteModel(
            name='Analog',
        ),
    ]
