# Generated by Django 3.2.22 on 2023-12-18 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WykazFarb', '0004_alter_new_paint_analogs_hex_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_paint_analogs',
            name='Style',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
