# Generated by Django 3.2.22 on 2023-11-27 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('WykazFarb', '0005_alter_paint_sets_paints'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paint_sets',
            name='user',
        ),
        migrations.AlterField(
            model_name='collection',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='element',
            name='paint_sets',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WykazFarb.paint_sets'),
        ),
    ]
