# Generated by Django 4.1.6 on 2023-02-13 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WykazFarb', '0005_collection_alter_set_user_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Set',
        ),
    ]
