# Generated by Django 3.2.22 on 2023-11-27 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('WykazFarb', '0006_auto_20231127_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='paint_sets',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
