# Generated by Django 3.2.24 on 2024-02-28 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WykazFarb', '0006_remove_new_paint_analogs_style'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paint',
            name='analog',
        ),
        migrations.AddField(
            model_name='paint',
            name='hex',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WykazFarb.new_paint_analogs'),
        ),
        migrations.AlterField(
            model_name='paint',
            name='brand',
            field=models.IntegerField(choices=[(1, 'Citadel'), (2, 'Vallejo Game Color'), (3, 'Vallejo Game Air'), (4, 'Old Citadel'), (4, 'Tamiya')]),
        ),
        migrations.AlterField(
            model_name='paint',
            name='type',
            field=models.IntegerField(choices=[(1, 'Regular'), (2, 'Wash'), (3, 'Ink'), (4, 'Contrast'), (5, 'Spray'), (6, 'Other')], null=True),
        ),
    ]
