# Generated by Django 4.1.6 on 2023-02-14 09:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('WykazFarb', '0007_set'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Set',
            new_name='Paint_Sets',
        ),
    ]
